Sync-web
dan9Protasenia/Web_server_task pull request #1
Opened 2023-12-15 16:15 UTC by dan9Protasenia

2023-12-16 16:24 UTC, dan9Protasenia commented
@RoTorEx

2023-12-19 19:12 UTC, RoTorEx commented
> @RoTorEx

Вот тут ревьюеры)
![image](https://github.com/dan9Protasenia/Web_server_task/assets/78344396/ec473b16-8ff6-47eb-a59b-fcd1593146fe)

2023-12-19 19:12 UTC, RoTorEx commented
Потыкав там ты можешь запрашивать ревью

2023-12-19 19:55 UTC, RoTorEx requested changes
Отлично. Подправь замечания и измени конечную ветку на какую-нибудь другую, потому что я мастер обновил добавив пару задач в тз. Так что Синк и асинк лей в новую ветку, потом уже эту новую ветку будет сливать в мастер, как он тебя будет актуальный

2023-12-19 19:55 UTC, RoTorEx commented on README.md
За доку лайк!

2023-12-19 19:55 UTC, RoTorEx commented on README.md
> +poetry run src/sync/main.py
Не на всех платформах будет работать. На ликсе и маке нужно будет давать разрешение на редактирование.

Запускай через `poetry run python -m src.sycn.main`. Таким образом ты правильно запустишь интерпретатор из корня приложения и импорты будут правильно работать через корень

2023-12-19 19:55 UTC, RoTorEx commented on README.md
> +locust -f locustfile.py
Не забудь уточнять, что надо либо попасть снала в `poetry shell`, или `poetry run locust ...`. Локально ничего может не быть из пакетов (вообще локально ничего и не должно быть, особенно на UNIX системах пип может ломаться, я так как-то из-за неправильного менеджмента пакетов пипа с системным питоном случайно сломал мак себе и делал полный ребут).

2023-12-19 19:55 UTC, RoTorEx commented on pyproject.toml
> +flake8 = "^6.1.0"
Это как линтер в большых проектах выносится в отдельную группу, которая в финальной сборке не нужна (на будущее)

2023-12-19 19:55 UTC, RoTorEx commented on README.md
> +pip install poetry
По причине ниже лучше так инсталить Poetry.
```
curl -sSL https://install.python-poetry.org | python - --version 1.7.1
```

2023-12-19 19:55 UTC, RoTorEx commented on src/setup.cfg
> +max-complexity = 8
Вынеси в __pyproject.toml__ это

2023-12-19 19:55 UTC, RoTorEx commented on src/sync/constant.py
> +port_sync = 8001
Хм, кажется ты можешь создать либо дата-класс, либо использовать встроенные строчные энамы для хранения переменных

2023-12-19 19:55 UTC, RoTorEx commented on src/sync/main.py
> +        response = "HTTP/1.1 404 Not Found\r\nContent-Type: text/plain\r\n\r\n404 Not Found"
Разбей полотно кода пробелами. Так же можешь сделать энам со всеми ответами, чтобы логику не награмождать, так же энами соответствуют `SSOT` принципу.

2023-12-19 19:55 UTC, RoTorEx commented on src/sync/main.py
> +from constant import LOCAL_HOST_SYNC, port_sync
Вот тут код упадёт. Попробуй импортировать и запускать всё из корня проекта.

2023-12-19 19:55 UTC, RoTorEx commented on src/sync/main.py
> +    response += "\r\nX-Custom-Header: MyCustomHeader"
Ты добавляешь это в конечный респонст как строку, а не в хэдеры

![image](https://github.com/dan9Protasenia/Web_server_task/assets/78344396/d45d3aaa-e27b-468a-926a-699e4fa9bbd7)

2024-01-14 20:27 UTC, merged