Feature async web
dan9Protasenia/Web_server_task pull request #2
Opened 2023-12-16 15:57 UTC by dan9Protasenia

2023-12-16 16:23 UTC, dan9Protasenia commented
@RoTorEx

2023-12-19 19:11 UTC, RoTorEx commented
> @RoTorEx

Вот тут ревьюеры)
![image](https://github.com/dan9Protasenia/Web_server_task/assets/78344396/ec473b16-8ff6-47eb-a59b-fcd1593146fe)

2023-12-19 19:12 UTC, RoTorEx commented
Потыкав там ты можешь запрашивать ревью

2023-12-19 20:08 UTC, RoTorEx requested changes
Можешь написать мэйк файл, который будет так же в корне лежать, чтобы не пришлось постоянно скакать с `cd` командой для запуска частей проектов (тесты, билд, локальный запуск, если есть и тд)

Мержи в другую ветку, в другом пр ответил.

2023-12-19 20:08 UTC, RoTorEx commented on src/async/pyproject.toml
Большая прелесть Poetry в том, ты можешь положить один pyproject.toml в корень и менеджить для каждой суб директории свои пакеты не смешивая их. Так должно быть с микросервисами, если они в монорепе лежат

2023-12-19 20:08 UTC, RoTorEx commented on src/tests/test_main.py
> +)
По-моему тут что-то сломано

2023-12-19 20:08 UTC, RoTorEx commented on src/tests/test_main.py
> +    pytest.main(["-v", "-s", __file__])
Так же определяй это в pyproject как конфиг.

2023-12-19 20:08 UTC, RoTorEx commented on src/async/main.py
> +async def error_middleware(app, handler):
Добавь пробелов внутри

2023-12-19 20:08 UTC, RoTorEx commented on src/async/consant.py
> +port = 8002
Можешь так же вынести все в энами, вместе с ответами от сервера

2023-12-19 20:08 UTC, RoTorEx commented on src/async/main.py
> +from consant import LOCAL_HOST, port
Та же проблема с импортом

2023-12-19 20:08 UTC, RoTorEx commented on src/async/Dockerfile
> +RUN pip install poetry
В другом пр показал как устанавливать Poetry лучше

2023-12-19 20:08 UTC, RoTorEx commented on README.md
По моему тут лайк!

2023-12-19 20:08 UTC, RoTorEx commented on src/async/Dockerfile
> +    && poetry install --no-dev --no-interaction --no-ansi
Вот тут ты как раз инсталишь без какой-то группы.

2023-12-19 20:08 UTC, RoTorEx commented on src/async/Dockerfile
> +
Blank lines

2023-12-19 20:08 UTC, RoTorEx commented on src/async/Dockerfile
Можешь почитать про мульти стейджинг и образ думаю раза в 2-1.5 получился ужать. Но это на отделыный пр и отдельную задачу оставь

2024-01-14 20:05 UTC, merged