Develop to master
dan9Protasenia/Web_server_task pull request #3
Opened 2024-01-14 20:36 UTC by dan9Protasenia

2024-01-14 21:28 UTC, dan9Protasenia commented
@RoTorEx

2024-01-15 14:37 UTC, RoTorEx requested changes
Хорошо
1. Смержи два поетри в один, разбив на группы, раздельные и, если надо, на какую-то общую.
2. Добавь тайпхинты, mypy может помочь с подсказками

2024-01-15 14:37 UTC, RoTorEx commented on README.md
> +This asynchronous web server is designed to handle concurrent network tasks efficiently using `asyncio` and `aiohttp`. It provides endpoints for various asynchronous operations, such as echoing JSON
Два описания?)

2024-01-15 14:37 UTC, RoTorEx commented on src/sync/main.py
> +        return
Лишние ретурн. В ендпоинте должен быть только один вход и один выход

2024-01-15 14:37 UTC, RoTorEx commented on src/sync/main.py
> +        handle_request(conn)
Добавь зактырие соединения и завершение работы если пришёл SIGINT или SIGKILL

2024-01-15 14:37 UTC, RoTorEx commented on src/tests/test_main_async.py
> +    pytest.main(["-v", "-s", __file__])
Сейчас везде используется pytest. Используй его, создай отдельный команду для запуска в makefile. Отдельный запуск тестов таким образом не лучшая идея

2024-01-15 14:37 UTC, RoTorEx commented on src/tests/test_main_sync.py
> +from Web_server_task.src.sync.main import handle_request
Что с импортом? При открытии проекта как корень правильно в папке Web server task этот импорт сломается

2024-01-15 14:37 UTC, RoTorEx commented on Makefile
> +	@$(POETRY_RUN_SYNC)
Не понимаю, в чём смысл?

2024-01-15 14:37 UTC, RoTorEx commented on src/tests/test_main_sync.py
> +    unittest.main()
Тоже самое, используй pytest, собери запуск как команда в Makefile

2024-01-15 14:37 UTC, RoTorEx commented on Makefile
> +	@$(POETRY_RUN_SYNC)
Названия запутанные, приходится долго бегать по файлу глазами мэтчить что за что отвечает и запускат

2024-01-15 14:37 UTC, RoTorEx commented on src/async_main/main.py
> +    return web.Response(text=HTTPResponse.IO_TASK.value)
Почему тут выделил return дополнительным отступом, а выше нет?

Я в целом всегда его выделяю как окончание блока исполнения

2024-01-15 14:37 UTC, RoTorEx commented on src/sync/pyproject.toml
> +max-complexity = 8
Добавь себе ещё blake и isort как форматтеры

2024-01-17 16:59 UTC, RoTorEx requested changes

2024-01-17 16:59 UTC, RoTorEx commented on src/app/async_main/Dockerfile
> +COPY ../../../pyproject.toml poetry.lock ./
Любое изменение этих файлов в проекте будет пересобирать весь образ полностью. Так что их копирование должно идти в верхних слоях (в конце файла). Так же путь до файла странный. Ты собриаешь докер из корня, когда флаг `-f` используешь, копируй просто через `COPY poetry.lock pyproject.toml ./`, только рабочую директорию правильно ставь

2024-01-17 16:59 UTC, RoTorEx commented on src/app/async_main/Dockerfile
> +WORKDIR /usr/src/app
Я думаю, что работаю директория должна закачиваться где начинается корень твоего проекта, то есть например `/server/web_server_task`, дальше, ты копируешь файлы и папки внутрь и импорты не поломаются, потмоу что они будет идти по тех же путям, что и локально у тебя на машине

2024-01-17 16:59 UTC, RoTorEx commented on src/app/async_main/Dockerfile
> +COPY . .
Не стоит так делать

2024-01-17 16:59 UTC, RoTorEx commented on src/app/async_main/Dockerfile
> +    && poetry install --no-dev --no-interaction --no-ansi
Для чего этот конфиг?

2024-01-17 16:59 UTC, RoTorEx commented on src/app/async_main/Dockerfile
> +ENV POETRY_VERSION=1.7.1
Лишний слой, он тебе не нужен, можешь сразу класть эту единственную переменную

2024-01-17 16:59 UTC, RoTorEx commented on src/app/async_main/Dockerfile
> +RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*
Через слеш команды раскидай на разные строки

2024-01-17 16:59 UTC, RoTorEx commented on src/app/async_main/main.py
> +    return middleware_handler
Следует держать только один ретурн везде

2024-01-17 16:59 UTC, RoTorEx commented on src/app/async_main/main.py
> +async def error_middleware(app: web.Application, handler) -> web.Response:
Заимпорти Application и Response в скоп, и ставь аннотации напрямую

2024-01-17 16:59 UTC, RoTorEx commented on src/app/async_main/main.py
> +                                                                     longitude=float(longitude))
Форматирование

2024-01-17 16:59 UTC, RoTorEx commented on src/app/async_main/main.py
> +        raise web.HTTPBadRequest(reason="Missing latitude or longitude parameter")
Красиво

2024-01-17 16:59 UTC, RoTorEx commented on src/app/sync/Dockerfile
Тут тоже самое всё

2024-01-17 16:59 UTC, RoTorEx commented on src/app/async_main/Dockerfile
> +    && poetry install --no-dev --no-interaction --no-ansi
И так же группы устанавливать через poetry install --with <group_name>

2024-01-17 16:59 UTC, RoTorEx commented on src/app/core/weather_api/weather_client.py
> +            'current_weather': True
Чтобы форматтер оставил такую структуру закончи последнюю строку запятой

2024-01-17 16:59 UTC, RoTorEx commented on src/app/core/weather_api/weather_client.py
> +            return CurrentWeatherData(**data)
Не делай так. Используй `BaseModel.validate_model()` или `BaseModel.dump_model()`, если у тебя Pydantic >2.0

2024-01-17 16:59 UTC, RoTorEx commented on src/app/core/weather_api/weather_client.py
> +            return CurrentWeatherData(**data)
Тоже самое

2024-01-17 16:59 UTC, RoTorEx commented on src/app/async_main/Dockerfile
[Для примера мульти-стейджинг с Poetry](https://github.com/RoTorEx/Bachaterio/blob/master/Dockerfile)

2024-01-17 16:59 UTC, RoTorEx commented on src/app/core/weather_api/weather_client.py
> +    weathercode: int
Схему положи в отдельный пакет `schemas` внутри `core`

2024-01-17 16:59 UTC, RoTorEx commented on src/app/core/weather_api/__init__.py
Я бы создал пакет `modules` и внутрь просто положи модуль `weather_api.py`, например.

Так же не забывай во все __init__.py добавлять `__all__ = [...]`

2024-01-17 16:59 UTC, RoTorEx commented on src/app/sync/constant.py
Энами тоже заслуживают лежать в `core` в пакете `enums`

2024-01-17 16:59 UTC, RoTorEx commented on src/tests/constant.py
Отдельный пакет для энамов?
но только если это не конфиг, конфиг для запуска должен лежать выше

2024-01-17 16:59 UTC, RoTorEx commented on src/tests/test_main_async.py
> +from Web_server_task.src.app.async_main.main import create_app
Неправильный импорт

2024-01-17 16:59 UTC, RoTorEx commented on src/tests/__init__.py
Вынеси тесты выше на уровень, они в коре лежать, это как бы не сурсы проекта

2024-01-17 16:59 UTC, RoTorEx commented on src/tests/test_main_sync.py
Окей, как-то это сложно выглядит, я думал ты просто запустишь тест сервер и проверишь только `hello` ручку

2024-01-17 16:59 UTC, RoTorEx commented on src/tests/test_main_sync.py
> +from unittest.mock import MagicMock, call, patch
У Pytest есть классные моки, но здесь ты заморочился конечно, пускай будет так

2024-01-18 19:06 UTC, dan9Protasenia commented on src/app/async_main/Dockerfile
> +    && poetry install --no-dev --no-interaction --no-ansi
я читал что poetry изолирует все свои зависимости в вирт среде 
false - чтобы poetry не создавал новую вирт среду так как у нас для этого есть docker

2024-01-20 17:59 UTC, merged